# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {H:/EECS_443/Xilinx_Vivado_Projects/lab_4/8-to-3 Priority Encoder/8-to-3 Priority Encoder.cache/wt} [current_project]
set_property parent.project_path {H:/EECS_443/Xilinx_Vivado_Projects/lab_4/8-to-3 Priority Encoder/8-to-3 Priority Encoder.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {{H:/EECS_443/Xilinx_Vivado_Projects/lab_4/8-to-3 Priority Encoder/8-to-3 Priority Encoder.srcs/sources_1/new/Encoder8to3.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/EECS_443/Xilinx_Vivado_Projects/lab_4/8-to-3 Priority Encoder/8-to-3 Priority Encoder.srcs/constrs_1/imports/lab_4/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{H:/EECS_443/Xilinx_Vivado_Projects/lab_4/8-to-3 Priority Encoder/8-to-3 Priority Encoder.srcs/constrs_1/imports/lab_4/Nexys4_Master.xdc}}]


synth_design -top priority_encoder -part xc7a100tcsg324-1


write_checkpoint -force -noxdef priority_encoder.dcp

catch { report_utilization -file priority_encoder_utilization_synth.rpt -pb priority_encoder_utilization_synth.pb }
