# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/EECS_443/Xilinx_Vivado_Projects/lab_2/4_BIT_COMPARATOR/4_BIT_COMPARATOR.cache/wt [current_project]
set_property parent.project_path H:/EECS_443/Xilinx_Vivado_Projects/lab_2/4_BIT_COMPARATOR/4_BIT_COMPARATOR.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib H:/EECS_443/Xilinx_Vivado_Projects/lab_2/4_BIT_COMPARATOR/4_BIT_COMPARATOR.srcs/sources_1/new/four_BIT_COMPARATOR.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/EECS_443/Xilinx_Vivado_Projects/lab_2/4_BIT_COMPARATOR/4_BIT_COMPARATOR.srcs/constrs_1/imports/lab_2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files H:/EECS_443/Xilinx_Vivado_Projects/lab_2/4_BIT_COMPARATOR/4_BIT_COMPARATOR.srcs/constrs_1/imports/lab_2/Nexys4_Master.xdc]


synth_design -top four_BIT_COMPARATOR -part xc7a100tcsg324-1


write_checkpoint -force -noxdef four_BIT_COMPARATOR.dcp

catch { report_utilization -file four_BIT_COMPARATOR_utilization_synth.rpt -pb four_BIT_COMPARATOR_utilization_synth.pb }
