set_property SRC_FILE_INFO {cfile:H:/EECS_443/Xilinx_Vivado_Projects/lab_1/lab_1.srcs/constrs_1/imports/EECS_443/lab1_2.xdc rfile:../../../lab_1.srcs/constrs_1/imports/EECS_443/lab1_2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {A}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {B}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports {S}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {C}]
