# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/EECS_443/Xilinx_Vivado_Projects/lab_2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path H:/EECS_443/Xilinx_Vivado_Projects/lab_2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib H:/EECS_443/Xilinx_Vivado_Projects/lab_2/project_2/project_2.srcs/sources_1/imports/lab_2/FULL_ADDER.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/EECS_443/Xilinx_Vivado_Projects/lab_2/project_2/project_2.srcs/constrs_1/imports/lab_2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files H:/EECS_443/Xilinx_Vivado_Projects/lab_2/project_2/project_2.srcs/constrs_1/imports/lab_2/Nexys4_Master.xdc]


synth_design -top FULL_ADDER -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FULL_ADDER.dcp

catch { report_utilization -file FULL_ADDER_utilization_synth.rpt -pb FULL_ADDER_utilization_synth.pb }
